### ISSUE TITLE
I have problems with tmp/ui_login.h

### ISSUE THREAD

**Issue by xdien** [xtuple/openrpt#46]
openrpt/common/login.h:30: error: tmp/ui_login.h: No such file or directory
how to solve the problem?

**Comment by gilmoskowitz** [comment]
@xdien - Missing `ui_something.h` errors usually occur when dependencies change but the `.pro` file has not been updated or `qmake` has not been run. Also make sure you use qmake, Qt Designer, and other Qt tools from the same Qt release.

Try this and let us know what happens:

```
$ cd /your/source/dir/for/openrpt
$ make distclean
$ qmake
$ make
```

This should clean up all of the pieces of your failed OpenRPT build and start fresh. If this does not work, please send us the output of the following commands:

```
$ cd /your/source/dir/for/openrpt
$ qmake --version
$ head Makefile
$ git status
$ git log | head
```

**Comment by xdien** [comment]
I apologize for the late reply. I have a letter run and it worked well, maybe I forgot to run qmake. Thank you so much
$ Make distclean
$ qmake
$ make
